### PR TITLE
Add short -h and -p host and port options

### PR DESCRIPTION
**Pull request by tremby**
Same as MPC.

### CODE REVIEW

**Comment by tremby** [comment]
Rationale: I run three MPD servers at home, and setting MPD_HOST each time is a pain.

**Comment by tremby** [comment]
Oh, `-h` conflicts with the help option.

I personally would prefer `-h` to be host, to match mpc, and help to be only `--help`. Thoughts?

**Comment by ambientsound** [comment]
I agree that `-h` is more effective than setting an environment variable or using the longer `--host`. It is also an intuitive flag, as `h` for host is widely used in other software. Also I would expect users to try `--help` if `-h` doesn't yield the help output.

In short, yes, I support using `-h` as shorthand for `--host`.

**Comment by ambientsound** [comment]
Please resolve the conflict, then I'll merge this.

**Comment by tremby** [comment]
Excellent; I shall make the necessary edits.

**Comment by tremby** [comment]
No idea how to override `-h` being the short version of `--help`!

I asked over on https://github.com/jessevdk/go-flags/issues/240 -- stand by...

**Comment by tremby** [comment]
I wonder if you can take a look at that? I got stuck and haven't had a response from them in a while.

**Comment by ambientsound** [comment]
The go-flags solution for this seems hackish at best. I'm going to suggest that, for the sake of readability , maintainability, and code quality, we use another flag as shorthand (for instance `-s` for _server_). The alternative would be to not provide a shorthand at all.

**Comment by tremby** [comment]
Hmm, I don't like it. Homogeneity of these basic options between the various MPD tools is very important in my opinion.

I've posted again over at go-flags asking the maintainer to consider three other possible solutions on their end.

**Comment by kimtore** [comment]
Environment variables seems like the cross-setup way to do this, closing.

**Pull request closed without merging**
